parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:jest/recommended
  - prettier
  - prettier/@typescript-eslint
plugins:
  - "@typescript-eslint"
  - jest
rules:
  eqeqeq: ['error', 'allow-null']
  indent: off # prettier!
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: ignore
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      peerDependencies: true
      optionalDependencies: false
  import/prefer-default-export: off
