parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
plugins:
  - "@typescript-eslint"
  - jest
rules:
  eqeqeq: ["error", "allow-null"]
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: ignore
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      peerDependencies: true
      optionalDependencies: false
  import/prefer-default-export: off
  radix: error
  prefer-promise-reject-errors: error
  no-throw-literal: error
  guard-for-in: warn
  jest/valid-expect: error
  dot-notation: error
  no-loop-func: error
  no-extra-bind: error
  linebreak-style:
    - error
    - unix
