// flow-typed signature: 8324a4e9ad65d119a29d3e62d6c64b18
// flow-typed version: <<STUB>>/archiver_v0.14.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'archiver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'archiver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'archiver/lib/archiver' {
  declare module.exports: any;
}

declare module 'archiver/lib/core' {
  declare module.exports: any;
}

declare module 'archiver/lib/plugins/json' {
  declare module.exports: any;
}

declare module 'archiver/lib/plugins/tar' {
  declare module.exports: any;
}

declare module 'archiver/lib/plugins/zip' {
  declare module.exports: any;
}

declare module 'archiver/lib/util/file' {
  declare module.exports: any;
}

declare module 'archiver/lib/util/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'archiver/lib/archiver.js' {
  declare module.exports: $Exports<'archiver/lib/archiver'>;
}
declare module 'archiver/lib/core.js' {
  declare module.exports: $Exports<'archiver/lib/core'>;
}
declare module 'archiver/lib/plugins/json.js' {
  declare module.exports: $Exports<'archiver/lib/plugins/json'>;
}
declare module 'archiver/lib/plugins/tar.js' {
  declare module.exports: $Exports<'archiver/lib/plugins/tar'>;
}
declare module 'archiver/lib/plugins/zip.js' {
  declare module.exports: $Exports<'archiver/lib/plugins/zip'>;
}
declare module 'archiver/lib/util/file.js' {
  declare module.exports: $Exports<'archiver/lib/util/file'>;
}
declare module 'archiver/lib/util/index.js' {
  declare module.exports: $Exports<'archiver/lib/util/index'>;
}
