// flow-typed signature: 68552197f03ce0f67ef84996ae1816cd
// flow-typed version: <<STUB>>/extract-docs_v^1.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-docs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-docs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-docs/cli' {
  declare module.exports: any;
}

declare module 'extract-docs/extractDocs' {
  declare module.exports: any;
}

declare module 'extract-docs/package' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-docs/cli.js' {
  declare module.exports: $Exports<'extract-docs/cli'>;
}
declare module 'extract-docs/extractDocs.js' {
  declare module.exports: $Exports<'extract-docs/extractDocs'>;
}
declare module 'extract-docs/package.js' {
  declare module.exports: $Exports<'extract-docs/package'>;
}
