// flow-typed signature: 132f2bab1474fbfe8e904e426cb13e57
// flow-typed version: <<STUB>>/fstream_v1.0.7/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fstream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fstream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fstream/examples/filter-pipe' {
  declare module.exports: any;
}

declare module 'fstream/examples/pipe' {
  declare module.exports: any;
}

declare module 'fstream/examples/reader' {
  declare module.exports: any;
}

declare module 'fstream/examples/symlink-write' {
  declare module.exports: any;
}

declare module 'fstream/fstream' {
  declare module.exports: any;
}

declare module 'fstream/lib/abstract' {
  declare module.exports: any;
}

declare module 'fstream/lib/collect' {
  declare module.exports: any;
}

declare module 'fstream/lib/dir-reader' {
  declare module.exports: any;
}

declare module 'fstream/lib/dir-writer' {
  declare module.exports: any;
}

declare module 'fstream/lib/file-reader' {
  declare module.exports: any;
}

declare module 'fstream/lib/file-writer' {
  declare module.exports: any;
}

declare module 'fstream/lib/get-type' {
  declare module.exports: any;
}

declare module 'fstream/lib/link-reader' {
  declare module.exports: any;
}

declare module 'fstream/lib/link-writer' {
  declare module.exports: any;
}

declare module 'fstream/lib/proxy-reader' {
  declare module.exports: any;
}

declare module 'fstream/lib/proxy-writer' {
  declare module.exports: any;
}

declare module 'fstream/lib/reader' {
  declare module.exports: any;
}

declare module 'fstream/lib/socket-reader' {
  declare module.exports: any;
}

declare module 'fstream/lib/writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fstream/examples/filter-pipe.js' {
  declare module.exports: $Exports<'fstream/examples/filter-pipe'>;
}
declare module 'fstream/examples/pipe.js' {
  declare module.exports: $Exports<'fstream/examples/pipe'>;
}
declare module 'fstream/examples/reader.js' {
  declare module.exports: $Exports<'fstream/examples/reader'>;
}
declare module 'fstream/examples/symlink-write.js' {
  declare module.exports: $Exports<'fstream/examples/symlink-write'>;
}
declare module 'fstream/fstream.js' {
  declare module.exports: $Exports<'fstream/fstream'>;
}
declare module 'fstream/lib/abstract.js' {
  declare module.exports: $Exports<'fstream/lib/abstract'>;
}
declare module 'fstream/lib/collect.js' {
  declare module.exports: $Exports<'fstream/lib/collect'>;
}
declare module 'fstream/lib/dir-reader.js' {
  declare module.exports: $Exports<'fstream/lib/dir-reader'>;
}
declare module 'fstream/lib/dir-writer.js' {
  declare module.exports: $Exports<'fstream/lib/dir-writer'>;
}
declare module 'fstream/lib/file-reader.js' {
  declare module.exports: $Exports<'fstream/lib/file-reader'>;
}
declare module 'fstream/lib/file-writer.js' {
  declare module.exports: $Exports<'fstream/lib/file-writer'>;
}
declare module 'fstream/lib/get-type.js' {
  declare module.exports: $Exports<'fstream/lib/get-type'>;
}
declare module 'fstream/lib/link-reader.js' {
  declare module.exports: $Exports<'fstream/lib/link-reader'>;
}
declare module 'fstream/lib/link-writer.js' {
  declare module.exports: $Exports<'fstream/lib/link-writer'>;
}
declare module 'fstream/lib/proxy-reader.js' {
  declare module.exports: $Exports<'fstream/lib/proxy-reader'>;
}
declare module 'fstream/lib/proxy-writer.js' {
  declare module.exports: $Exports<'fstream/lib/proxy-writer'>;
}
declare module 'fstream/lib/reader.js' {
  declare module.exports: $Exports<'fstream/lib/reader'>;
}
declare module 'fstream/lib/socket-reader.js' {
  declare module.exports: $Exports<'fstream/lib/socket-reader'>;
}
declare module 'fstream/lib/writer.js' {
  declare module.exports: $Exports<'fstream/lib/writer'>;
}
