// flow-typed signature: 278c57f9fc274873b03497a7c3a2ec11
// flow-typed version: <<STUB>>/jest-html_v^1.3.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-html/lib/common/types' {
  declare module.exports: any;
}

declare module 'jest-html/lib/previewer' {
  declare module.exports: any;
}

declare module 'jest-html/lib/serializer/hyphenateStyleName' {
  declare module.exports: any;
}

declare module 'jest-html/lib/serializer/index' {
  declare module.exports: any;
}

declare module 'jest-html/lib/server/extractor' {
  declare module.exports: any;
}

declare module 'jest-html/lib/server/httpServer' {
  declare module.exports: any;
}

declare module 'jest-html/lib/server/startup' {
  declare module.exports: any;
}

declare module 'jest-html/lib/server/webpackConfig' {
  declare module.exports: any;
}

declare module 'jest-html/public/assets/app.bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-html/lib/common/types.js' {
  declare module.exports: $Exports<'jest-html/lib/common/types'>;
}
declare module 'jest-html/lib/previewer.js' {
  declare module.exports: $Exports<'jest-html/lib/previewer'>;
}
declare module 'jest-html/lib/serializer/hyphenateStyleName.js' {
  declare module.exports: $Exports<'jest-html/lib/serializer/hyphenateStyleName'>;
}
declare module 'jest-html/lib/serializer/index.js' {
  declare module.exports: $Exports<'jest-html/lib/serializer/index'>;
}
declare module 'jest-html/lib/server/extractor.js' {
  declare module.exports: $Exports<'jest-html/lib/server/extractor'>;
}
declare module 'jest-html/lib/server/httpServer.js' {
  declare module.exports: $Exports<'jest-html/lib/server/httpServer'>;
}
declare module 'jest-html/lib/server/startup.js' {
  declare module.exports: $Exports<'jest-html/lib/server/startup'>;
}
declare module 'jest-html/lib/server/webpackConfig.js' {
  declare module.exports: $Exports<'jest-html/lib/server/webpackConfig'>;
}
declare module 'jest-html/public/assets/app.bundle.js' {
  declare module.exports: $Exports<'jest-html/public/assets/app.bundle'>;
}
