// flow-typed signature: a87e60844a47bf45b07f20afe48d679e
// flow-typed version: <<STUB>>/jest-html_v^1.3.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-html/__mocks__/node-uuid' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/components/000-root' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/components/010-app' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/components/015-appContents' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/components/110-sidebar' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/components/115-sidebarItem' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/components/120-preview' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/components/200-largeMessage' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/gral/constants' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/gral/helpers' {
  declare module.exports: any;
}

declare module 'jest-html/lib/client/startup' {
  declare module.exports: any;
}

declare module 'jest-html/lib/common/types' {
  declare module.exports: any;
}

declare module 'jest-html/lib/previewer' {
  declare module.exports: any;
}

declare module 'jest-html/lib/serializer/hyphenateStyleName' {
  declare module.exports: any;
}

declare module 'jest-html/lib/serializer/index' {
  declare module.exports: any;
}

declare module 'jest-html/lib/server/extractor' {
  declare module.exports: any;
}

declare module 'jest-html/lib/server/httpServer' {
  declare module.exports: any;
}

declare module 'jest-html/lib/server/startup' {
  declare module.exports: any;
}

declare module 'jest-html/lib/server/webpackConfig' {
  declare module.exports: any;
}

declare module 'jest-html/public/assets/app.bundle' {
  declare module.exports: any;
}

declare module 'jest-html/src/common/types' {
  declare module.exports: any;
}

declare module 'jest-html/src/previewer' {
  declare module.exports: any;
}

declare module 'jest-html/src/serializer/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'jest-html/src/serializer/hyphenateStyleName' {
  declare module.exports: any;
}

declare module 'jest-html/src/serializer/index' {
  declare module.exports: any;
}

declare module 'jest-html/src/server/__tests__/extractor.test' {
  declare module.exports: any;
}

declare module 'jest-html/src/server/extractor' {
  declare module.exports: any;
}

declare module 'jest-html/src/server/httpServer' {
  declare module.exports: any;
}

declare module 'jest-html/src/server/startup' {
  declare module.exports: any;
}

declare module 'jest-html/src/server/webpackConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-html/__mocks__/node-uuid.js' {
  declare module.exports: $Exports<'jest-html/__mocks__/node-uuid'>;
}
declare module 'jest-html/lib/client/components/000-root.js' {
  declare module.exports: $Exports<'jest-html/lib/client/components/000-root'>;
}
declare module 'jest-html/lib/client/components/010-app.js' {
  declare module.exports: $Exports<'jest-html/lib/client/components/010-app'>;
}
declare module 'jest-html/lib/client/components/015-appContents.js' {
  declare module.exports: $Exports<'jest-html/lib/client/components/015-appContents'>;
}
declare module 'jest-html/lib/client/components/110-sidebar.js' {
  declare module.exports: $Exports<'jest-html/lib/client/components/110-sidebar'>;
}
declare module 'jest-html/lib/client/components/115-sidebarItem.js' {
  declare module.exports: $Exports<'jest-html/lib/client/components/115-sidebarItem'>;
}
declare module 'jest-html/lib/client/components/120-preview.js' {
  declare module.exports: $Exports<'jest-html/lib/client/components/120-preview'>;
}
declare module 'jest-html/lib/client/components/200-largeMessage.js' {
  declare module.exports: $Exports<'jest-html/lib/client/components/200-largeMessage'>;
}
declare module 'jest-html/lib/client/gral/constants.js' {
  declare module.exports: $Exports<'jest-html/lib/client/gral/constants'>;
}
declare module 'jest-html/lib/client/gral/helpers.js' {
  declare module.exports: $Exports<'jest-html/lib/client/gral/helpers'>;
}
declare module 'jest-html/lib/client/startup.js' {
  declare module.exports: $Exports<'jest-html/lib/client/startup'>;
}
declare module 'jest-html/lib/common/types.js' {
  declare module.exports: $Exports<'jest-html/lib/common/types'>;
}
declare module 'jest-html/lib/previewer.js' {
  declare module.exports: $Exports<'jest-html/lib/previewer'>;
}
declare module 'jest-html/lib/serializer/hyphenateStyleName.js' {
  declare module.exports: $Exports<'jest-html/lib/serializer/hyphenateStyleName'>;
}
declare module 'jest-html/lib/serializer/index.js' {
  declare module.exports: $Exports<'jest-html/lib/serializer/index'>;
}
declare module 'jest-html/lib/server/extractor.js' {
  declare module.exports: $Exports<'jest-html/lib/server/extractor'>;
}
declare module 'jest-html/lib/server/httpServer.js' {
  declare module.exports: $Exports<'jest-html/lib/server/httpServer'>;
}
declare module 'jest-html/lib/server/startup.js' {
  declare module.exports: $Exports<'jest-html/lib/server/startup'>;
}
declare module 'jest-html/lib/server/webpackConfig.js' {
  declare module.exports: $Exports<'jest-html/lib/server/webpackConfig'>;
}
declare module 'jest-html/public/assets/app.bundle.js' {
  declare module.exports: $Exports<'jest-html/public/assets/app.bundle'>;
}
declare module 'jest-html/src/common/types.js' {
  declare module.exports: $Exports<'jest-html/src/common/types'>;
}
declare module 'jest-html/src/previewer.js' {
  declare module.exports: $Exports<'jest-html/src/previewer'>;
}
declare module 'jest-html/src/serializer/__tests__/index.test.js' {
  declare module.exports: $Exports<'jest-html/src/serializer/__tests__/index.test'>;
}
declare module 'jest-html/src/serializer/hyphenateStyleName.js' {
  declare module.exports: $Exports<'jest-html/src/serializer/hyphenateStyleName'>;
}
declare module 'jest-html/src/serializer/index.js' {
  declare module.exports: $Exports<'jest-html/src/serializer/index'>;
}
declare module 'jest-html/src/server/__tests__/extractor.test.js' {
  declare module.exports: $Exports<'jest-html/src/server/__tests__/extractor.test'>;
}
declare module 'jest-html/src/server/extractor.js' {
  declare module.exports: $Exports<'jest-html/src/server/extractor'>;
}
declare module 'jest-html/src/server/httpServer.js' {
  declare module.exports: $Exports<'jest-html/src/server/httpServer'>;
}
declare module 'jest-html/src/server/startup.js' {
  declare module.exports: $Exports<'jest-html/src/server/startup'>;
}
declare module 'jest-html/src/server/webpackConfig.js' {
  declare module.exports: $Exports<'jest-html/src/server/webpackConfig'>;
}
