// flow-typed signature: 96567d510b92e808869eebf1b2f7f52a
// flow-typed version: <<STUB>>/sax_v1.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sax/examples/example' {
  declare module.exports: any;
}

declare module 'sax/examples/get-products' {
  declare module.exports: any;
}

declare module 'sax/examples/hello-world' {
  declare module.exports: any;
}

declare module 'sax/examples/pretty-print' {
  declare module.exports: any;
}

declare module 'sax/lib/sax' {
  declare module.exports: any;
}

declare module 'sax/test/attribute-name' {
  declare module.exports: any;
}

declare module 'sax/test/attribute-no-space' {
  declare module.exports: any;
}

declare module 'sax/test/bom' {
  declare module.exports: any;
}

declare module 'sax/test/buffer-overrun' {
  declare module.exports: any;
}

declare module 'sax/test/case' {
  declare module.exports: any;
}

declare module 'sax/test/cdata-chunked' {
  declare module.exports: any;
}

declare module 'sax/test/cdata-end-split' {
  declare module.exports: any;
}

declare module 'sax/test/cdata-fake-end' {
  declare module.exports: any;
}

declare module 'sax/test/cdata-multiple' {
  declare module.exports: any;
}

declare module 'sax/test/cdata' {
  declare module.exports: any;
}

declare module 'sax/test/cyrillic' {
  declare module.exports: any;
}

declare module 'sax/test/duplicate-attribute' {
  declare module.exports: any;
}

declare module 'sax/test/emoji' {
  declare module.exports: any;
}

declare module 'sax/test/end_empty_stream' {
  declare module.exports: any;
}

declare module 'sax/test/entities' {
  declare module.exports: any;
}

declare module 'sax/test/entity-mega' {
  declare module.exports: any;
}

declare module 'sax/test/flush' {
  declare module.exports: any;
}

declare module 'sax/test/index' {
  declare module.exports: any;
}

declare module 'sax/test/issue-23' {
  declare module.exports: any;
}

declare module 'sax/test/issue-30' {
  declare module.exports: any;
}

declare module 'sax/test/issue-35' {
  declare module.exports: any;
}

declare module 'sax/test/issue-47' {
  declare module.exports: any;
}

declare module 'sax/test/issue-49' {
  declare module.exports: any;
}

declare module 'sax/test/issue-84' {
  declare module.exports: any;
}

declare module 'sax/test/issue-86' {
  declare module.exports: any;
}

declare module 'sax/test/parser-position' {
  declare module.exports: any;
}

declare module 'sax/test/script-close-better' {
  declare module.exports: any;
}

declare module 'sax/test/script' {
  declare module.exports: any;
}

declare module 'sax/test/self-closing-child-strict' {
  declare module.exports: any;
}

declare module 'sax/test/self-closing-child' {
  declare module.exports: any;
}

declare module 'sax/test/self-closing-tag' {
  declare module.exports: any;
}

declare module 'sax/test/stand-alone-comment' {
  declare module.exports: any;
}

declare module 'sax/test/stray-ending' {
  declare module.exports: any;
}

declare module 'sax/test/trailing-attribute-no-value' {
  declare module.exports: any;
}

declare module 'sax/test/trailing-non-whitespace' {
  declare module.exports: any;
}

declare module 'sax/test/unclosed-root' {
  declare module.exports: any;
}

declare module 'sax/test/unquoted' {
  declare module.exports: any;
}

declare module 'sax/test/utf8-split' {
  declare module.exports: any;
}

declare module 'sax/test/xml_entities' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-as-tag-name' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-issue-41' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-rebinding' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-strict' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-unbound-element' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-unbound' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-xml-default-ns' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-xml-default-prefix-attribute' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-xml-default-prefix' {
  declare module.exports: any;
}

declare module 'sax/test/xmlns-xml-default-redefine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sax/examples/example.js' {
  declare module.exports: $Exports<'sax/examples/example'>;
}
declare module 'sax/examples/get-products.js' {
  declare module.exports: $Exports<'sax/examples/get-products'>;
}
declare module 'sax/examples/hello-world.js' {
  declare module.exports: $Exports<'sax/examples/hello-world'>;
}
declare module 'sax/examples/pretty-print.js' {
  declare module.exports: $Exports<'sax/examples/pretty-print'>;
}
declare module 'sax/lib/sax.js' {
  declare module.exports: $Exports<'sax/lib/sax'>;
}
declare module 'sax/test/attribute-name.js' {
  declare module.exports: $Exports<'sax/test/attribute-name'>;
}
declare module 'sax/test/attribute-no-space.js' {
  declare module.exports: $Exports<'sax/test/attribute-no-space'>;
}
declare module 'sax/test/bom.js' {
  declare module.exports: $Exports<'sax/test/bom'>;
}
declare module 'sax/test/buffer-overrun.js' {
  declare module.exports: $Exports<'sax/test/buffer-overrun'>;
}
declare module 'sax/test/case.js' {
  declare module.exports: $Exports<'sax/test/case'>;
}
declare module 'sax/test/cdata-chunked.js' {
  declare module.exports: $Exports<'sax/test/cdata-chunked'>;
}
declare module 'sax/test/cdata-end-split.js' {
  declare module.exports: $Exports<'sax/test/cdata-end-split'>;
}
declare module 'sax/test/cdata-fake-end.js' {
  declare module.exports: $Exports<'sax/test/cdata-fake-end'>;
}
declare module 'sax/test/cdata-multiple.js' {
  declare module.exports: $Exports<'sax/test/cdata-multiple'>;
}
declare module 'sax/test/cdata.js' {
  declare module.exports: $Exports<'sax/test/cdata'>;
}
declare module 'sax/test/cyrillic.js' {
  declare module.exports: $Exports<'sax/test/cyrillic'>;
}
declare module 'sax/test/duplicate-attribute.js' {
  declare module.exports: $Exports<'sax/test/duplicate-attribute'>;
}
declare module 'sax/test/emoji.js' {
  declare module.exports: $Exports<'sax/test/emoji'>;
}
declare module 'sax/test/end_empty_stream.js' {
  declare module.exports: $Exports<'sax/test/end_empty_stream'>;
}
declare module 'sax/test/entities.js' {
  declare module.exports: $Exports<'sax/test/entities'>;
}
declare module 'sax/test/entity-mega.js' {
  declare module.exports: $Exports<'sax/test/entity-mega'>;
}
declare module 'sax/test/flush.js' {
  declare module.exports: $Exports<'sax/test/flush'>;
}
declare module 'sax/test/index.js' {
  declare module.exports: $Exports<'sax/test/index'>;
}
declare module 'sax/test/issue-23.js' {
  declare module.exports: $Exports<'sax/test/issue-23'>;
}
declare module 'sax/test/issue-30.js' {
  declare module.exports: $Exports<'sax/test/issue-30'>;
}
declare module 'sax/test/issue-35.js' {
  declare module.exports: $Exports<'sax/test/issue-35'>;
}
declare module 'sax/test/issue-47.js' {
  declare module.exports: $Exports<'sax/test/issue-47'>;
}
declare module 'sax/test/issue-49.js' {
  declare module.exports: $Exports<'sax/test/issue-49'>;
}
declare module 'sax/test/issue-84.js' {
  declare module.exports: $Exports<'sax/test/issue-84'>;
}
declare module 'sax/test/issue-86.js' {
  declare module.exports: $Exports<'sax/test/issue-86'>;
}
declare module 'sax/test/parser-position.js' {
  declare module.exports: $Exports<'sax/test/parser-position'>;
}
declare module 'sax/test/script-close-better.js' {
  declare module.exports: $Exports<'sax/test/script-close-better'>;
}
declare module 'sax/test/script.js' {
  declare module.exports: $Exports<'sax/test/script'>;
}
declare module 'sax/test/self-closing-child-strict.js' {
  declare module.exports: $Exports<'sax/test/self-closing-child-strict'>;
}
declare module 'sax/test/self-closing-child.js' {
  declare module.exports: $Exports<'sax/test/self-closing-child'>;
}
declare module 'sax/test/self-closing-tag.js' {
  declare module.exports: $Exports<'sax/test/self-closing-tag'>;
}
declare module 'sax/test/stand-alone-comment.js' {
  declare module.exports: $Exports<'sax/test/stand-alone-comment'>;
}
declare module 'sax/test/stray-ending.js' {
  declare module.exports: $Exports<'sax/test/stray-ending'>;
}
declare module 'sax/test/trailing-attribute-no-value.js' {
  declare module.exports: $Exports<'sax/test/trailing-attribute-no-value'>;
}
declare module 'sax/test/trailing-non-whitespace.js' {
  declare module.exports: $Exports<'sax/test/trailing-non-whitespace'>;
}
declare module 'sax/test/unclosed-root.js' {
  declare module.exports: $Exports<'sax/test/unclosed-root'>;
}
declare module 'sax/test/unquoted.js' {
  declare module.exports: $Exports<'sax/test/unquoted'>;
}
declare module 'sax/test/utf8-split.js' {
  declare module.exports: $Exports<'sax/test/utf8-split'>;
}
declare module 'sax/test/xml_entities.js' {
  declare module.exports: $Exports<'sax/test/xml_entities'>;
}
declare module 'sax/test/xmlns-as-tag-name.js' {
  declare module.exports: $Exports<'sax/test/xmlns-as-tag-name'>;
}
declare module 'sax/test/xmlns-issue-41.js' {
  declare module.exports: $Exports<'sax/test/xmlns-issue-41'>;
}
declare module 'sax/test/xmlns-rebinding.js' {
  declare module.exports: $Exports<'sax/test/xmlns-rebinding'>;
}
declare module 'sax/test/xmlns-strict.js' {
  declare module.exports: $Exports<'sax/test/xmlns-strict'>;
}
declare module 'sax/test/xmlns-unbound-element.js' {
  declare module.exports: $Exports<'sax/test/xmlns-unbound-element'>;
}
declare module 'sax/test/xmlns-unbound.js' {
  declare module.exports: $Exports<'sax/test/xmlns-unbound'>;
}
declare module 'sax/test/xmlns-xml-default-ns.js' {
  declare module.exports: $Exports<'sax/test/xmlns-xml-default-ns'>;
}
declare module 'sax/test/xmlns-xml-default-prefix-attribute.js' {
  declare module.exports: $Exports<'sax/test/xmlns-xml-default-prefix-attribute'>;
}
declare module 'sax/test/xmlns-xml-default-prefix.js' {
  declare module.exports: $Exports<'sax/test/xmlns-xml-default-prefix'>;
}
declare module 'sax/test/xmlns-xml-default-redefine.js' {
  declare module.exports: $Exports<'sax/test/xmlns-xml-default-redefine'>;
}
