// flow-typed signature: ce2ba6495f16f3c31142c53792fa6913
// flow-typed version: <<STUB>>/sax_v1.2.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sax/lib/sax' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sax/lib/sax.js' {
  declare module.exports: $Exports<'sax/lib/sax'>;
}
